import pandas as pd
import yfinance as yf
import ta
import numpy as np
import os
from ai_trader.config.settings import DATA_DIR

class DataProcessor:
    def __init__(self):
        pass

    def fetch_data(self, ticker, start_date="2020-01-01", end_date=None):
        """Fetches historical data for a ticker using yfinance."""
        print(f"Fetching data for {ticker}...")
        try:
            df = yf.download(ticker, start=start_date, end=end_date, progress=False)
            if df.empty:
                raise ValueError(f"No data found for {ticker}")

            # yfinance often returns MultiIndex columns if multiple tickers, but we do one by one.
            # Flatten if necessary or standardise columns
            if isinstance(df.columns, pd.MultiIndex):
                df = df.xs(ticker, axis=1, level=1)

            # Ensure standard columns exist
            required_cols = ['Open', 'High', 'Low', 'Close', 'Volume']
            if not all(col in df.columns for col in required_cols):
                 # Try to handle case where columns might be lower case
                df.columns = [c.capitalize() for c in df.columns]

            # Handle missing values
            df = df.ffill().dropna()
            return df
        except Exception as e:
            print(f"Error fetching data for {ticker}: {e}")
            return None

    def add_technicals(self, df, features_config=None):
        """
        Adds technical indicators to the DataFrame.
        features_config: list of feature names to include. If None, calculates all available.
        """
        if df is None or df.empty:
            return None

        df = df.copy()

        # --- Trend Indicators ---
        # MACD
        macd = ta.trend.MACD(close=df['Close'])
        df['MACD'] = macd.macd()
        df['Signal'] = macd.macd_signal()
        df['Hist'] = macd.macd_diff()

        # EMA / SMA
        df['EMA_20'] = ta.trend.EMAIndicator(close=df['Close'], window=20).ema_indicator()
        df['SMA_50'] = ta.trend.SMAIndicator(close=df['Close'], window=50).sma_indicator()
        df['SMA_200'] = ta.trend.SMAIndicator(close=df['Close'], window=200).sma_indicator()
        df['Dist_EMA200'] = df['Close'] - df['SMA_200'] # Distance from 200 SMA

        # ADX
        df['ADX'] = ta.trend.ADXIndicator(high=df['High'], low=df['Low'], close=df['Close']).adx()

        # --- Momentum Indicators ---
        # RSI
        df['RSI'] = ta.momentum.RSIIndicator(close=df['Close']).rsi()

        # Stochastic Oscillator
        stoch = ta.momentum.StochasticOscillator(high=df['High'], low=df['Low'], close=df['Close'])
        df['Stoch_K'] = stoch.stoch()
        df['Stoch_D'] = stoch.stoch_signal()

        # CCI
        df['CCI'] = ta.trend.CCIIndicator(high=df['High'], low=df['Low'], close=df['Close']).cci()

        # --- Volatility Indicators ---
        # Bollinger Bands
        bb = ta.volatility.BollingerBands(close=df['Close'])
        df['BB_Upper'] = bb.bollinger_hband()
        df['BB_Lower'] = bb.bollinger_lband()
        df['BB_Mid'] = bb.bollinger_mavg()

        # ATR
        df['ATR'] = ta.volatility.AverageTrueRange(high=df['High'], low=df['Low'], close=df['Close']).average_true_range()

        # --- Volume Indicators ---
        # MFI
        df['MFI'] = ta.volume.MFIIndicator(high=df['High'], low=df['Low'], close=df['Close'], volume=df['Volume']).money_flow_index()

        # Returns
        df['Returns'] = df['Close'].pct_change()

        # Clean NaN values generated by indicators (e.g., first 200 rows for SMA200)
        df = df.dropna()

        # Filter columns if config is provided
        if features_config:
            # Always keep OHLCV and Returns for base logic
            base_cols = ['Open', 'High', 'Low', 'Close', 'Volume', 'Returns']
            cols_to_keep = list(set(base_cols + features_config))
            # Ensure columns exist before filtering
            existing_cols = [c for c in cols_to_keep if c in df.columns]
            df = df[existing_cols]

        return df

    def get_processed_data(self, ticker, start_date, end_date, features_config=None, use_vix=False):
        """Orchestrates fetching and processing."""
        df = self.fetch_data(ticker, start_date, end_date)
        if df is None: return None

        df = self.add_technicals(df, features_config)

        if use_vix:
            vix_df = self.fetch_data("^VIX") # US VIX or regional equivalent? Defaulting to CBOE VIX
            if vix_df is not None:
                # Align VIX data
                vix_df = vix_df[['Close']].rename(columns={'Close': 'VIX_Close'})
                df = df.join(vix_df).ffill().dropna()

        return df

    def save_data(self, df, ticker):
        file_path = os.path.join(DATA_DIR, f"{ticker}_processed.csv")
        df.to_csv(file_path)
        return file_path
